function socialLinks(){return `<a href="mailto:grmaykov@gmail.com" class="social-link" aria-label="Email Grigory Maykov" title="grmaykov@gmail.com"><svg width="26" height="26" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M2 3h20a2 2 0 0 1 2 2v14a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2Zm0 2v1.7l10 7 10-7V5l-10 7L2 5Z" fill-rule="evenodd"/></svg></a><a href="https://t.me/grifonius" target="_blank" rel="noopener" class="social-link" aria-label="Telegram @grifonius" title="Telegram @grifonius"><svg width="26" height="26" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M21.44 3.12 2.98 10.24c-1.26.5-1.25 1.2-.23 1.51l4.74 1.48 1.82 5.57c.22.61.11.85.75.85.5 0 .73-.23 1.01-.5l2.3-2.24 4.78 3.53c.88.49 1.51.24 1.73-.82l3.13-14.74c.32-1.28-.49-1.86-1.57-1.38ZM8.23 12.89l10.69-6.74c.53-.32 1.01-.15.61.2l-8.82 7.96-.34 3.64-2.14-5.06Z"/></svg></a><a href="https://www.instagram.com/gmaykov/" target="_blank" rel="noopener" class="social-link" aria-label="Instagram" title="Instagram"><img src="/assets/instagram.svg" alt="" width="26" height="26"></a><a href="https://www.imdb.com/name/nm12058267/" target="_blank" rel="noopener" class="social-link" aria-label="IMDb" title="IMDb"><img src="/assets/imdb.svg" alt="" width="26" height="26"></a><a href="https://www.kinopoisk.ru/name/5196316/" target="_blank" rel="noopener" class="social-link" aria-label="Кинопоиск" title="Кинопоиск"><img src="/assets/kinopoisk.svg" alt="" width="26" height="26"></a><a href="https://www.facebook.com/grisha.maykov" target="_blank" rel="noopener" class="social-link" aria-label="Facebook" title="Facebook"><img src="/assets/facebook.svg" alt="" width="26" height="26"></a>`;}
let lang='en', data, currentGallery=[], currentIndex=0;
const $=s=>document.querySelector(s), t=(en,ru)=>lang==='ru'?ru:en;
const titles=[['Kuba, Marina','Куба, Марина'],['A Place Far from Home','Место далеко от дома'],['My Boyfriend, the Mannequin','Мой парень, манекен'],['Toli','Толи'],['Vow','Обет'],['When Starlight Passes By','Моя хорошая звезда'],['Paraglider','Параплан'],['Kuivazi Life','Жизнь в Куйвози'],['Living Your Own Life','Жить своей жизнью'],['Video · 10','Видео · 10'],['Video · 11','Видео · 11'],['Kazuskoma — I Can’t','Казускома — Я не могу']];
const directors=[['Konstantin Bogoslavsky','Константин Богославский'],['Diana Mashanova','Диана Машанова'],['Dmitry Nikolenko','Дмитрий Николенко'],['Diana Mashanova','Диана Машанова'],['Nikolay Flotsky','Николай Флотский'],['Denis Bazovoy','Денис Базовой'],['Grigory Maykov','Григорий Майков'],['Grigory Maykov','Григорий Майков'],['Nikolay Flotsky','Николай Флотский']];
const name=i=>i<6?titles[i][0]+' / '+titles[i][1]:i===8?'Жить своей жизнью':i===11?'КАЗУСКОМА — Я НЕ МОГУ':(i===9||i===10)&&data.projects[i].title?data.projects[i].title:titles[i][0]; const kind=i=>i<3?t('Feature film','Полный метр'):i<6?t('Short film','Короткий метр'):i<9?t('Documentary','Документальное кино'):t('Video','Видео');
const img=(src,alt,large=false)=>`<img src="/${src}" ${large?'fetchpriority="high"':'loading="lazy"'} decoding="async" alt="${alt}" ${large?'':`srcset="/${src.replace('.webp','-sm.webp')} 640w, /${src} 1920w" sizes="(max-width:750px) 90vw, 46vw"`}>`;
function chrome(){document.documentElement.lang=lang;$('.brand').innerHTML=`${t('GRIGORY MAYKOV','ГРИГОРИЙ МАЙКОВ')}<small>${t('Director of photography','Оператор-постановщик')}</small>`;$('nav').innerHTML=`<a href="#work">${t('Films','Кино')}</a><a href="#photography">${t('Photography','Фотография')}</a><a href="#about">${t('About','Обо мне')}</a><a href="#equipment">${t('Equipment','Техника')}</a><a href="#contact">${t('Contact','Контакты')}</a>`;$('footer').innerHTML=`<div class="footer-bottom"><span>© ${new Date().getFullYear()} ${t('Grigory Maykov','Григорий Майков')}</span><div class="socials">${socialLinks()}</div><a href="#work">${t('Back to films','К фильмам')} ↑</a></div>`;}
function awardBadge(){return `<div class="film-award"><img src="/assets/atlff-2025-official.png" width="72" height="92" alt="Atlanta Film Festival 2025" loading="lazy"><div><span class="film-award-label">WINNER · ATLANTA 2025</span><strong>Best Cinematography</strong><span class="film-award-presenter">Presented by Panavision and Light Iron</span></div></div>`;}
function card(i){const p=data.projects[i];return `<article class="project"><div class="frame">${img(p.poster||p.images[0],name(i))}<button class="preview-play" onclick="playPreview(this,${i})" aria-label="Play ${name(i)}"><span class="preview-play-label"><svg width="18" height="18" viewBox="0 0 24 24" fill="currentColor" aria-hidden="true"><path d="M8 5.5a.75.75 0 0 1 1.14-.64l10 6.5a.75.75 0 0 1 0 1.28l-10 6.5A.75.75 0 0 1 8 18.5z"/></svg></span></button></div><a class="caption" href="#film/${i}"><div><h3>${name(i)}</h3>${i>=9&&i<=11?'':`<p>${directors[i]?t('Directed by ','Режиссёр — ')+t(...directors[i]):kind(i)}</p>`}</div><span>${i===9||i===11?'Music video':i===10?'Experimental video':kind(i)}</span></a>${p.images.length?`<a class="stills-hint" href="#film/${i}">Watch stills <span aria-hidden="true">→</span></a>`:''}${i===1?awardBadge():''}</article>`;}
function playPreview(button,i){const host=button.closest('.frame,.hero');if(!host)return;document.querySelectorAll('.preview-playing').forEach(el=>{el.innerHTML=el._previewMarkup;el.classList.remove('preview-playing');});host._previewMarkup=host.innerHTML;const frame=document.createElement('iframe');frame.src=data.projects[i].embed+(data.projects[i].embed.includes('?')?'&':'?')+'autoplay=1';frame.title=name(i);frame.allow='autoplay; fullscreen; picture-in-picture';frame.allowFullscreen=true;host.replaceChildren(frame);host.classList.add('preview-playing');window.siteEvent?.('play_video',{film:name(i),placement:'homepage'});}

function home(){return `<section class="hero">${img('assets/video-028.webp','A Place Far from Home — film still',true)}<div class="hero-copy"><h1>A Place Far from Home</h1><p class="hero-russian">Место далеко от дома</p><div class="sub">${t('Best Cinematography · Atlanta Film Festival 2025','Лучшая операторская работа · Atlanta Film Festival 2025')}</div></div></section><div class="wrap"><div class="section-head"><h2>${t('Selected films','Избранные фильмы')}</h2></div><div class="grid">${[0,1,2,3,4,5].map(card).join('')}</div><div class="archive"><div class="grid">${data.projects.slice(6).map((p,n)=>card(n+6)).join('')}</div></div></div>`;}
let photoIndex=0,photoGesture=null,photoLastSwipe=0;
function photoSlides(){const total=data.photo.length;return [-1,0,1].map(offset=>{const i=(photoIndex+offset+total)%total;const image=img(data.photo[i].src,'Photograph by Grigory Maykov · '+(i+1),offset===0);return offset===0?`<button class="photo-slide photo-center" onclick="if(Date.now()-photoLastSwipe>400)openGallery('photo',${i})" aria-label="Open photograph full screen">${image}</button>`:`<button class="photo-slide ${offset<0?'photo-left':'photo-right'}" onclick="if(Date.now()-photoLastSwipe>400)movePhoto(${offset})" aria-label="${offset<0?'Previous photograph':'Next photograph'}">${image}</button>`;}).join('');}
function movePhoto(n){photoIndex=(photoIndex+n+data.photo.length)%data.photo.length;$('#photo-slides').innerHTML=photoSlides();$('#photo-position').textContent=(photoIndex+1)+' / '+data.photo.length;}
function photoSwipeStart(e){if(!e.isPrimary||e.button>0)return;photoGesture={x:e.clientX,y:e.clientY,id:e.pointerId};}
function photoSwipeEnd(e){if(!photoGesture||photoGesture.id!==e.pointerId)return;const dx=e.clientX-photoGesture.x,dy=e.clientY-photoGesture.y;photoGesture=null;if(Math.abs(dx)>40&&Math.abs(dx)>Math.abs(dy)*1.2){photoLastSwipe=Date.now();movePhoto(dx<0?1:-1);}}
function photo(){return `<section class="photo-carousel photo-full" oncontextmenu="return false" ondragstart="return false" aria-label="Photography carousel" aria-roledescription="carousel"><div class="photo-slides" id="photo-slides" onpointerdown="photoSwipeStart(event)" onpointerup="photoSwipeEnd(event)" onpointercancel="photoGesture=null" onpointerleave="if(event.pointerType==='mouse')photoGesture=null">${photoSlides()}</div><div class="photo-controls"><button onclick="movePhoto(-1)" aria-label="Previous photograph">←</button><span id="photo-position" aria-live="polite" aria-atomic="true">${photoIndex+1} / ${data.photo.length}</span><button onclick="movePhoto(1)" aria-label="Next photograph">→</button></div></section>`;}

function about(){return `<div class="wrap"><div class="page-title"><div class="eyebrow">${t('Behind the camera','По ту сторону камеры')}</div></div><div class="bio"><div>${img('assets/old-site-001.webp',t('Grigory Maykov','Григорий Майков'),true)}</div><div><p class="lead">${t('The story comes first.','Сначала — история.')}</p><p>${t('My interest in photography gradually grew into a passion for filmmaking. Both photography and painting remain important sources of inspiration for me and continue to influence my work as a cinematographer.','Моё увлечение фотографией постепенно привело меня в кино. Фотография и живопись по-прежнему вдохновляют меня и влияют на мою работу оператором.')}</p><p>${t('Finding a film’s visual language starts with understanding the story and what we want to say through it. I approach each script with an open mind, letting its tone and meaning shape my work. For me, every shot should serve the story.','Поиск визуального языка фильма начинается с понимания истории и того, что мы хотим ею сказать. Я стараюсь подходить к каждому сценарию без готовых решений: именно его настроение и смысл определяют мою работу. Для меня каждый кадр должен работать на историю.')}</p><p>${t('My debut feature as a cinematographer, A Place Far from Home, received the Best Cinematography award at the 2025 Atlanta Film Festival, with a prize package provided by Panavision and Light Iron.','Мой дебютный полный метр «Место далеко от дома» получил награду за лучшую операторскую работу на Atlanta Film Festival в 2025 году и призовой пакет от Panavision и Light Iron.')}</p><p>${t('I welcome projects across different formats and scales, from independent features to commercials, fashion films, and music videos. What matters most to me is a story I connect with and a strong creative relationship with the director — a sense that we understand each other and want to explore the same ideas.','Мне интересны проекты разных форматов и масштаба: от независимого кино до рекламы, fashion-фильмов и музыкальных клипов. Главное — история, которая мне близка, и творческое взаимопонимание с режиссёром: ощущение, что мы смотрим в одну сторону и хотим говорить об одном.')}</p><p>${t('For producers and production companies, I can also provide camera equipment through my own rental house.','Для продюсеров и продакшн-компаний: я также могу предоставить съёмочную технику из своего рентала.')}</p><a class="back" href="#equipment">${t('Explore the equipment','Посмотреть технику')} ↗</a></div></div></div>`;}
const equipmentGroups=[
 {title:'Cameras',items:[
 ['ARRI ALEXA Mini','',[8,67,166,197]],['ARRI ALEXA Mini LF','',[178,66,153,198]],['ARRI ALEXA 35','',[330,67,166,197]],['Sony VENICE 2','',[496, 60, 180, 204],'polygon(19.444% 0.490%,82.778% 0.490%,86.111% 10.294%,98.889% 10.294%,98.889% 28.431%,90.000% 36.275%,91.111% 54.412%,98.333% 60.784%,98.333% 81.373%,90.000% 94.118%,74.444% 99.020%,35.000% 97.059%,0.556% 86.765%,0.556% 30.882%,18.333% 25.490%)'],['ARRI SR3','',[675, 91, 151, 172],'polygon(13.245% 6.395%,58.940% 6.395%,58.940% 16.860%,51.656% 20.930%,69.536% 20.349%,82.119% 27.907%,84.106% 43.605%,97.351% 47.093%,97.351% 68.023%,100.000% 73.837%,100.000% 86.047%,61.589% 86.628%,56.291% 94.767%,9.934% 94.767%,9.934% 44.767%,0.000% 41.279%,0.000% 27.907%,12.583% 22.674%)'],['Nikon R10','',[813, 96, 204, 165],'polygon(0.490% 6.061%,14.706% 3.030%,26.961% 10.303%,32.843% 2.424%,78.431% 7.879%,88.235% 17.576%,99.020% 13.939%,99.020% 56.364%,91.667% 53.333%,83.824% 72.121%,62.745% 67.273%,62.745% 93.333%,56.863% 97.576%,36.765% 95.758%,35.784% 63.030%,25.000% 53.939%,20.098% 40.606%,7.843% 36.364%,0.490% 25.455%)']]},
 {title:'Lenses',items:[
 ['ZEISS Standard Prime','16 · 24 · 28 · 32 · 40 · 50 · 85 · 135 mm',[6,357,515,207]],['LOMO Standard Speed','18 · 22 · 28 · 35 · 50 · 75 mm',[544,360,465,205]],['Atlas Orion Anamorphic','32 · 40 · 50 · 65 · 80 · 100 mm',[6,635,530,170]],['LOMO Anamorphic Roundfront','40 · 50 · 75 · 100 mm',[576,624,433,194]],['P+S TECHNOVISION','40 · 50 · 75 · 100 · 135 mm',[7,861,404,239]],['Angénieux 10–120','Super 16 · 10–120 mm',[433,927,365,173]],['Kinoptik Tegea','5.7 mm',[827,877,176,223]]]},
 {title:'Gimbals',items:[['ARRI Maxima','',[180,1167,267,332],'polygon(30% 0,100% 0,100% 100%,0 100%,0 17%,30% 17%)'],['Cyclo Lite','',[594,1183,319,311]]]}];
const equipmentAssets={'ARRI ALEXA Mini':'gear-mini-original.webp','ARRI ALEXA Mini LF':'gear-mini-lf-original.webp','ARRI ALEXA 35':'gear-alexa35-original.webp','Sony VENICE 2':'gear-venice-original.webp','ARRI SR3':'gear-sr3-original.webp','Nikon R10':'gear-nikon-original.webp','ZEISS Standard Prime':'gear-zeiss-original.webp','LOMO Standard Speed':'gear-lomo-original.webp','Atlas Orion Anamorphic':'gear-atlas-original.webp','LOMO Anamorphic Roundfront':'gear-lomo-anamorphic-original.webp','P+S TECHNOVISION':'gear-technovision-original.webp','Angénieux 10–120':'gear-angenieux-original.webp','Kinoptik Tegea':'gear-kinoptik-original.webp','ARRI Maxima':'gear-maxima-original.webp','Cyclo Lite':'gear-cyclo-original.webp'};
function equipmentCard(item){const [label,detail]=item;return `<article class="gear-card"><div class="gear-image-area"><img class="gear-original ${label==='ARRI ALEXA Mini'?'gear-black-source':''}" src="/assets/${equipmentAssets[label]}" alt="${label}" loading="lazy" decoding="async"></div><h3>${label}</h3>${detail?`<p>${detail}</p>`:''}</article>`;}

function equipment(){return `<div class="wrap gear-page"><div class="page-title"><div class="eyebrow">For producers & production companies</div><h1>Equipment</h1><p>Camera, lens and stabilization packages available through my own rental house.</p></div>${equipmentGroups.map(g=>`<section class="gear-section"><div class="section-head"><h2>${g.title}</h2></div><div class="gear-grid gear-${g.title.toLowerCase()}">${g.items.map(equipmentCard).join('')}</div></section>`).join('')}</div>`;}

function film(i){const p=data.projects[i];return `<div class="wrap"><a class="back" href="#work">← ${t('All films','Все фильмы')}</a><div class="page-title"><div class="eyebrow">${kind(i)}${i===1?' · Atlanta Film Festival 2025':''}</div><h1>${name(i)}</h1>${directors[i]?`<p>${t('Directed by ','Режиссёр — ')+t(...directors[i])}<br>${t('Cinematography by Grigory Maykov','Оператор — Григорий Майков')}</p>`:''}</div>${i===1?awardBadge():''}<div class="player" id="player">${p.poster||p.images.length?img(p.poster||p.images[0],name(i),true):'<div class="empty-art">'+name(i)+'</div>'}<button onclick="playFilm(${i})"><span class="play-icon">▷</span>${t('Play video','Смотреть видео')}</button></div><a class="back" href="${p.embed}" target="_blank" rel="noopener">${t('Open video in a new tab','Открыть видео в новой вкладке')} ↗</a><div class="film-stills">${p.images.map((s,n)=>`<button onclick="openGallery('${i}',${n})" aria-label="${t('Open still','Открыть кадр')} ${n+1}">${img(s,name(i)+' · '+(n+1))}</button>`).join('')}</div><a class="back" href="#film/${(i+1)%data.projects.length}">${t('Next film','Следующий фильм')} — ${name((i+1)%data.projects.length)} →</a></div>`;}
function playFilm(i){window.siteEvent?.("play_video",{film:name(i)});const frame=document.createElement('iframe');frame.src=data.projects[i].embed+(data.projects[i].embed.includes('?')?'&':'?')+'autoplay=1';frame.title=name(i);frame.allow='autoplay; fullscreen; picture-in-picture';frame.allowFullscreen=true;$('#player').replaceChildren(frame);}
function openGallery(key,i){window.siteEvent?.(key==='photo'?"open_photo":"open_still",{collection:key==='photo'?"Photography":name(+key),image:i+1});currentGallery=key==='photo'?data.photo.map(x=>x.src):data.projects[+key].images;currentIndex=i;$('#lightbox').classList.toggle('photo-protected',key==='photo');$('#light-image').draggable=false;$('#light-image').oncontextmenu=key==='photo'?()=>false:null;updateLight();$('#lightbox').showModal();document.body.style.overflow='hidden';}function updateLight(){$('#light-image').src='/'+currentGallery[currentIndex];$('#light-image').alt=t('Image','Изображение')+' '+(currentIndex+1);$('#light-count').textContent=`${currentIndex+1} / ${currentGallery.length}`;}function step(n){currentIndex=(currentIndex+n+currentGallery.length)%currentGallery.length;updateLight();}function closeLight(){$('#lightbox').close();document.body.style.overflow='';}

function render(scroll=true){chrome();const route=location.hash.slice(1)||'work';let html;if(route==='contact')html=contact();else if(route==='photography')html=photo();else if(route==='about')html=about();else if(route==='equipment')html=equipment();else if(/^film\/\d+$/.test(route)&&data.projects[+route.split('/')[1]])html=film(+route.split('/')[1]);else html=home();$('#content').innerHTML=html;document.title=route==='contact'?'Contact — Grigory Maykov':(route.startsWith('film/')?name(+route.split('/')[1]):t('Grigory Maykov — Cinematographer','Григорий Майков — Оператор-постановщик'));document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.hash==='#'+route));window.sitePageView?.(route.startsWith('film/')?document.title:({contact:'Contact',work:'Films',photography:'Photography',about:'About',equipment:'Equipment'}[route]||'Films'));if(scroll){if(route==='contact')window.scrollTo({top:0,left:0,behavior:'instant'});else window.scrollTo(0,0);}}
window.addEventListener('hashchange',()=>render());document.addEventListener('keydown',e=>{if(e.key!=='ArrowLeft'&&e.key!=='ArrowRight')return;if(e.altKey||e.ctrlKey||e.metaKey||e.target?.isContentEditable||/^(INPUT|TEXTAREA|SELECT)$/.test(e.target?.tagName||''))return;const direction=e.key==='ArrowRight'?1:-1;if($('#lightbox').open){e.preventDefault();step(direction);}else if(location.hash==='#photography'&&data){e.preventDefault();movePhoto(direction);}});$('#lightbox').addEventListener('close',()=>document.body.style.overflow='');fetch('/data.json').then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>{data=d;render();}).catch(()=>{$('#content').innerHTML='<div class="wrap page-title"><h1>Grigory Maykov</h1><p>Please reload the page.</p><a href="mailto:grmaykov@gmail.com">grmaykov@gmail.com</a></div>';});

function contact(){return `<section class="contact-page wrap" aria-labelledby="contact-title"><div class="contact-page-inner"><h1 id="contact-title">Contact</h1><div class="contact-page-icons">${socialLinks()}</div></div></section>`;}
